# Generated by Django 3.0.1 on 2020-01-22 18:49

import django.db.models.deletion
import django.utils.timezone
import utils.helper
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routedb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="route",
            name="modification_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="route",
            name="uid",
            field=models.CharField(
                default=utils.helper.random_key,
                editable=False,
                max_length=12,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="athlete",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="name",
            field=models.CharField(blank=True, max_length=52),
        ),
    ]
