# Generated by Django 3.0.1 on 2020-01-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routedb", "0002_auto_20200122_1849"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="name",
            field=models.CharField(max_length=52),
        ),
    ]
