# Generated by Django 3.0.1 on 2020-01-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routedb', '0003_auto_20200123_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='country',
            field=models.CharField(default='FI', max_length=2),
            preserve_default=False,
        ),
    ]
