# Generated by Django 3.0.3 on 2020-02-24 17:07

import django_s3_storage.storage
import routedb.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routedb", "0005_route_tz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rastermap",
            name="image",
            field=models.ImageField(
                height_field="height",
                storage=django_s3_storage.storage.S3Storage(
                    aws_s3_bucket_name="drawmyroute-maps"
                ),
                upload_to=routedb.models.map_upload_path,
                width_field="width",
            ),
        ),
    ]
