# Generated by Django 3.0.3 on 2020-03-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routedb', '0006_auto_20200224_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
