# Generated by Django 3.0.5 on 2020-04-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routedb", "0007_auto_20200308_1530"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
