# Generated by Django 3.1.1 on 2020-09-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routedb", "0010_auto_20200901_1644"),
    ]

    operations = [
        migrations.AddField(
            model_name="rastermap",
            name="mime_type",
            field=models.CharField(
                default="image/jpeg", editable=False, max_length=256
            ),
        ),
    ]
