# Generated by Django 3.1.1 on 2020-09-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routedb', '0011_rastermap_mime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='has_image_thumbnail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='has_image_w_header',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='has_image_w_header_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='route',
            name='has_image_w_route',
            field=models.BooleanField(default=False),
        ),
    ]
