# Generated by Django 3.1.1 on 2020-09-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routedb', '0012_auto_20200912_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='has_image_blank',
            field=models.BooleanField(default=False),
        ),
    ]
