# Generated by Django 3.1.1 on 2020-10-17 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("routedb", "0013_route_has_image_blank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="strava_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
