# Generated by Django 3.1.1 on 2020-11-27 16:55

import utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("routedb", "0015_auto_20201127_1540"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rastermap",
            name="_latitude",
            field=models.FloatField(
                editable=False, validators=[utils.validators.validate_latitude]
            ),
        ),
        migrations.AlterField(
            model_name="rastermap",
            name="_longitude",
            field=models.FloatField(
                editable=False, validators=[utils.validators.validate_longitude]
            ),
        ),
        migrations.AlterField(
            model_name="rastermap",
            name="country",
            field=models.CharField(editable=False, max_length=2),
        ),
    ]
