# Generated by Django 3.2.4 on 2021-06-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routedb", "0016_auto_20201127_1655"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersettings",
            options={
                "verbose_name": "user settings",
                "verbose_name_plural": "user settings",
            },
        ),
    ]
