# Generated by Django 3.2.14 on 2022-07-18 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("routedb", "0018_usersettings_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="route",
            name="has_image_blank",
        ),
        migrations.RemoveField(
            model_name="route",
            name="has_image_thumbnail",
        ),
        migrations.RemoveField(
            model_name="route",
            name="has_image_w_header",
        ),
        migrations.RemoveField(
            model_name="route",
            name="has_image_w_header_route",
        ),
        migrations.RemoveField(
            model_name="route",
            name="has_image_w_route",
        ),
    ]
